### ISSUE TITLE
Personal List

### ISSUE THREAD

**Issue by 0XDE57** [JoseDeFreitas/awesome-youtubers#123]
Hello! This my personal list of the highest quality technical stemtubers. I don't have time to add descriptions to fit your format, but I think you will find some good entries:

https://github.com/0XDE57/STEM

**Comment by JoseDeFreitas** [comment]
Hello, @0XDE57. That's a lot of YouTube channels! I'm going to check them out and decide which ones to add to the list. I'll inform you here when I publish the commit and keep this issue open for you to comment any improvement or fix. I appreciate your interest.

**Comment by JoseDeFreitas** [comment]
Hello again, @0XDE57.

I deeply apologise for the excessive time that has passed since you first opened this issue until I got to work on adding the YouTubers you suggested.

I looked through the entire list and added the YouTubers I consider best fit this list and have a clear content quality (commits from a2dc1c2a53fc85f0ffc167f87ab4f3169c2f0906 to 695a8cd4315e844cddfb9740a74556b82760cbdc). Some sections go beyond the description of this list as they teach topics more related to other sciences, and some YouTubers were already on the list, but I still found more than 20 awesome channels to include.

I really thank you for bringing these channels to the list. I'll close this issue in a few days, but until then you can give me any feedback you like.

Have an awesome day!

**Comment by 0XDE57** [comment]
No worries for time, it was a big list. (and I have more to add now when I find the time/energy)

Glad you found some channels worthy of including!
