### ISSUE TITLE
Allow This Repository to Participate in Hacktoberfest?

### ISSUE THREAD

**Issue by xtrp** [JoseDeFreitas/awesome-youtubers#26]
Hi,

I was wondering if the maintainers would be open to allowing this repository to participate in the [Hacktoberfest 2020 open source challenge](https://hacktoberfest.digitalocean.com/)? It could be a positive way to help support the open source community and stimulate a few contributions. If so, I adding the `hacktoberfest` and `hacktoberfest2020` topics to this repo should allow it to participate.

Thanks for this great list of awesome YouTubers!

— Gabriel

**Comment by catcecilia** [comment]
I think you can contribute regardless of it being tagged hacktoberfest or hacktoberfest2020. However, it is up to JoseDeFreitas though :) they are the owner.  

I'm all for it if there are good contributions, not spammy ones (which is a known problem with Hacktober fest)

**Comment by RandoNandoz** [comment]
https://github.com/digitalocean/hacktoberfest/pull/596

Because of an influx of spam and low quality PRs in some repos, DigitalOcean and the hacktoberfest organizers have decided that you need a `hacktoberfest` tag for contributions to count towards your T-Shirt / Plant a tree quota.

**Comment by JoseDeFreitas** [comment]
Hello! I've added the "hacktoberfest" topic to the repository.

I asked some questions in the Hacktoberfet Discord server. As this repository is text-based, I felt it may not fit in this event. Comparing it to other repositories and projects, where you can change a lot of complex things, this repository doesn't involve literally any programming language or something challenging.

On the other hand, and because this is an awesome list, not every YouTuber should be here, but instead awesome YouTubers (I know, as many things we even don't think about them that way, it's subjective; but you can tell if a YouTuber has good tutorial videos depending on the topics they cover, how deeply they cover these topics, if you can understand what they're saying, and more aspects.) Because of that, I don't think it's that easy to select a properly YouTuber to be added to this list.

I'm not quite sure yet if this repository could have a part in the Hacktoberfest event, and if the people who contribute to it can have their PR counted for the event. Said that I'll keep this issue open for discussion. I don't know if it'll get accepted or blocked, so don't count on it 100% secure. Thank you for opening this issue and thank you for commenting!

**Comment by JoseDeFreitas** [comment]
Hacktoberfest just ended yesterday, so this is my comment about this issue now.
As one of the Hacktoberfest rules state, pull requests mature in 15 days. Because of that, in 15 days (11/16/20) I'll be closing this issue as well as removing the "hacktoberfest" topic from the repository.
Thank you to all of the users who contributed in this month 👻.

**Comment by JoseDeFreitas** [comment]
Time has passed. Thank you to all the contributors who helped grow this list with awesome YouTubers in the month of October 2020 🧡.
