### ISSUE TITLE
Add a spanish youtuber

### ISSUE THREAD

**Issue by memoriasIT** [JoseDeFreitas/awesome-youtubers#43]
Although it's a bit of a self-plug, I think I should send an issue with my YouTube channel.
https://www.youtube.com/c/memoriasdeuninformatico

I publish free courses in Spanish mostly related to computer science. I do not have a big fanbase but that doesn't stop me.
I strive for better quality in every video and I think it can be perceived.
Please consider adding my channel to the Spanish list :)

**Comment by JoseDeFreitas** [comment]
Hello @memoriasIT!
Thank you for the recommendation. I like your channel, I consider it has great tutorials. It's good to have more awesome Spanish channels added to the list.
What section do you think fits better? I've thought about "Programming in general" and "Computer sciences" but tell me what you think. The sections in the Spanish list file are **the same** as the main list, but they don't appear because there's no channel yet to add it to. If you want, I can add the channel by myself. Tell me if you will create a pull request.
Thank you!

**Comment by memoriasIT** [comment]
Thanks for the quick reply, I created a pull request.
https://github.com/JoseDeFreitas/awesome-youtubers/pull/44
