### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by shreyanshu28** [JoseDeFreitas/awesome-youtubers#7]
[**Florin Pop**](https://www.youtube.com/channel/UCeU-1X402kT-JlLdAitxSMA) : Web Development
[**LearnCode.academy**](https://www.youtube.com/user/learncodeacademy): Web Tutorials
[**LevelUpTuts**](https://www.youtube.com/user/LevelUpTuts) : Web Development
[**Programming with Mosh**](https://www.youtube.com/user/programmingwithmosh) : Web Development
[**Layout Land**](https://www.youtube.com/channel/UC7TizprGknbDalbHplROtag) : CSS

[**Java Brains**](https://www.youtube.com/user/koushks) : Java

[**Raw Coding**](https://www.youtube.com/channel/UCP_jWxjn__YXmo4iU7Low0g) : .NET 
[**Tim Corey**](https://www.youtube.com/user/IAmTimCorey) : .NET

[**Sentdex**](https://www.youtube.com/user/sentdex) : Machine Learning and AI

Edit : Added links to youtube channels
Edit from the replies : Removed Siraj Rawal
 **Tim Corey** : .NET
**Layout Land** : CSS

**Comment by Aendor** [comment]
**Tim Corey** : .NET

**Comment by Vijayabhaskar96** [comment]
Please no Siraj Raval, he is a controversial YouTuber.

**Comment by chauhanvats3** [comment]
**Layout Land** : CSS

**Comment by JoseDeFreitas** [comment]
Hello!
These are very good recommendations! I've looked through all of the channels and watched at least 1 video from every channel.
Some notes I want to point:

**Tim Corey**: in the comment you've posted it says its content is ".NET"-related, but I see mainly C# so that's why I've put the channel under the "Programming in general" section. I've seen ASP.NET videos so I also added the .NET "content about".
**sentdex**: this channel uploads mainly Python content, but it also uploads Raspberry PI tutorials. I've put this channel under the "Programming in general" section because it's not only Machine Learning (about what I've seen). Should I create a Machine Learning section?

I've already committed the changes (commit: 1e451915f35689d1fbcbea8c8bf874cdea7babb4).
If you want let me know your opinions, as well as any other change you would like to see. If you would like to work on editing an entry just tell me.
A lot of thanks! 🤝

**Comment by Vijayabhaskar96** [comment]
I suggest:
[Abhishek Thakur](https://www.youtube.com/user/abhisheksvnit) Machine Learning/Deep Learning
[Jeremy Howard](https://www.youtube.com/user/howardjeremyp) Machine Learning/Deep Learning (fastai courses are uploaded here)
 [Ahlad Kumar](https://www.youtube.com/channel/UCP9YJJ24w6g38VMVMm6Thtg) Machine Learning/Deep Learning
[AI Coffee Break with Letitia Parcalabescu](https://www.youtube.com/channel/UCobqgqE4i5Kf7wrxRxhToQA) Machine Learning/Deep Learning
[Aladdin Persson](https://www.youtube.com/channel/UCkzW5JSFwvKRjXABI-UTAkQ) Machine Learning/Deep Learning
[Andreas Mueller](https://www.youtube.com/channel/UCMEXgDffQy6nS2a74Gby8ZA) Machine Learning/Deep Learning
[CodingEntrepreneurs](https://www.youtube.com/c/CodingEntrepreneurs) Programming
[Data School](https://www.youtube.com/channel/UCnVzApLJE2ljPZSeQylSEyg)
[Henry AI Labs](https://www.youtube.com/channel/UCHB9VepY6kYvZjj0Bgxnpbw) Machine Learning/Deep Learning
[Rasa](https://www.youtube.com/channel/UCJ0V6493mLvqdiVwOKWBODQ) Machine Learning/Deep Learning
[Sebastiaan Mathôt](https://www.youtube.com/channel/UC6HfeAa0vWeSWS6IcNAjZ2A) Programming
[Two Minute Papers](https://www.youtube.com/channel/UCbfYPyITQ-7l4upoX8nvctg) Machine Learning/Deep Learning
[Yannic Kilcher](https://www.youtube.com/channel/UCZHmQk67mSJgfCCTn7xBfew) Machine Learning/Deep Learning
[Zachary Mueller](https://www.youtube.com/channel/UCmKoQOD8uBqsRS8XDdSgrlQ) Machine Learning/Deep Learning

I know this is a lot of Machine learning channels, I think they deserve their own section, What do you think?

**Comment by JoseDeFreitas** [comment]
Those are a lot of Machine Learning YouTubers! I'll take time while researching about them and watching some videos. It's clear that a Machine Learning section is needed, it's such a big topic to cover. Thank you so much for the recommendations @Vijayabhaskar96!

**Comment by JoseDeFreitas** [comment]
Hello @Vijayabhaskar96. I've reviewed the channels and added them, as well as the new Machine Learning section.
Commit: 796805d.
Let me know if you think the entries are good, or if you want to change something.
Thanks!
