### ISSUE TITLE
invalid link

### ISSUE THREAD

**Issue by arnavjindal** [JoseDeFreitas/awesome-youtubers#72]
Can't find channel "ICT tutorial channel" [here](https://github.com/JoseDeFreitas/awesome-youtubers#software-in-general).
has that channel banned or something like that..?

**Comment by JoseDeFreitas** [comment]
Hello! Thank you for bringing this to my attention.

I couldn't find any information regarding that channel in YouTube nor any other website. However, I found a reference to the channel in one website but I got a warning message from my browser telling me that it was insecure. I kept searching and found the channel statistics on a YouTube-ranking website. Luckily, that website was linking to the channel ID instead of the channel name. I searched for that ID on YouTube and found that the channel has been terminated due to copyright infringements. You can see [the website where I found the link](https://es.noxinfluencer.com/youtube/channel/UCvcRLDea021zU-qhYK6I48A) and the [YouTuber's channel link](https://www.youtube.com/channel/UCvcRLDea021zU-qhYK6I48A).

I removed the channel from the list in the 8f606746db14091d81dbf73030e55a418ca30075 commit.
