### ISSUE TITLE
I would like to make a field for competitive programming youtube channel

### ISSUE THREAD

**Issue by ritwikchakraborty123** [JoseDeFreitas/awesome-youtubers#79]

**Comment by JoseDeFreitas** [comment]
Hello @ritwikchakraborty123!

I don't know any awesome competitive programming YouTube channels, and new sections must be created with at least 1 YouTuber in them, but if you know one (or more) YouTubers, feel free to open a pull request adding both the new section (“Competitive programming”) and the YouTuber(s).

The section order is based on the popularity of the sections (according to what I think are the sections that people will first go to), but if you will, add the section in the position you want, preferable if it follows the “popularity criteria”.

I think it's a good idea to include this new section since that topic has become very popular. Thank you for recommending this and, as I previously wrote, feel free to open a pull request.

**Comment by JoseDeFreitas** [comment]
There are no updates on this issue, but I'll keep it open for people to know this suggestion and add this new section with at least 1 YouTube channel.

**Comment by ritwik-boringnews** [comment]
hi sir will like to add 2 or more YouTube channels for that section.
Can u assign me this task?

**Comment by JoseDeFreitas** [comment]
Hello again @ritwik-boringnews. Of course! I just assigned you to this issue. Thank you for your interest.

**Comment by JoseDeFreitas** [comment]
Some months have passed and there's no update about this issue; I'll keep it open if someone wants to create a list of competitive programming YouTubers, as I consider it's an interesting topic and useful for those who are into that world. My knowledge about this field is null, but if some day I decide to check out this topic I can add the channels that I consider awesome to the list.

**Comment by Dibakarroy1997** [comment]
Check out #93 
I added a new session `Interview and Competitive programming`.

I think we might also need some channel which covers Backend and DevOps. Things which comes under [backend roadmap](https://roadmap.sh/backend) or [DevOps roadmap](https://roadmap.sh/devops)

I know few in this topic:

- [TechWorld with Nana](https://www.youtube.com/c/TechWorldwithNana)
- [KodeKloud](https://www.youtube.com/c/KodeKloud)
- [Tech Primers](https://www.youtube.com/c/TechPrimers)
- [CodeOpinion](https://www.youtube.com/channel/UC3RKA4vunFAfrfxiJhPEplw)
- [Defog Tech](https://www.youtube.com/c/DefogTech)

Maybe will add it in new PR.

**Comment by JoseDeFreitas** [comment]
Hello, @Dibakarroy1997. Thank you for the PR you opened. I'm going to review it, and then we could add those channels you mention. It may be good to restructure the list by adding more categories for both DevOps and Backend.
