### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by MidlajYH** [JoseDeFreitas/awesome-youtubers#86]
![IMG_20220222_014848_376.jpg](https://user-images.githubusercontent.com/85442225/155021672-bf5e0042-8558-4286-b65b-6fedfc52a0b9.jpg)

When you tap Fireship it redirects to a different page, not youtube.

![Screenshot_2022-02-22-01-44-07-016_com.brave.browser.jpg](https://user-images.githubusercontent.com/85442225/155021749-971e325f-5d2c-4f8e-95bc-c9c40b35eda7.jpg)

**Comment by JoseDeFreitas** [comment]
Hello @MidlajYH! Fortunately, the channel does exist. The problem was that the owner changed its URL, so YouTube wasn't able to find a channel by that URL. I found out that the URL is the same as the channel name, so I fixed it. Commit that fixed the problem: d8d3c114b98ea55bc3a6e2c4c8447077f4c30b0a. Thank you for bringing up this issue.

**Comment by MidlajYH** [comment]
Thanks for fixing it :)
